Unstrip

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -290,13 +290,13 @@ pushd ${BUILD_DIR} > /dev/null
     ${EXEC_PHP} app/console cache:warmup --env=${SF_ENV}
 
 
-    echo "-------> Stripping cache dir"
-    echo "s/`strip_slashes $BUILD_DIR`/\/app\//g" > cache_strip.sed
-    find app/cache/ -type f -print0 | xargs -0 sed -i -f cache_strip.sed --quiet
-    if grep -r $BUILD_DIR app/cache -m 1 ; then
-        echo "----------> Error: Could still find ${BUILD_DIR} in cache"
-        exit 1
-    fi
+    #echo "-------> Stripping cache dir"
+    #echo "s/`strip_slashes $BUILD_DIR`/\/app\//g" > cache_strip.sed
+    #find app/cache/ -type f -print0 | xargs -0 sed -i -f cache_strip.sed --quiet
+    #if grep -r $BUILD_DIR app/cache -m 1 ; then
+    #    echo "----------> Error: Could still find ${BUILD_DIR} in cache"
+    #    exit 1
+    #fi
 
 popd > /dev/null
 
